[tool.poetry]
name = "misc_scripts"
version = "0.1.0"
description = ""
authors = ["Tyler Baur <tbaur@teuteberg.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.1.0"
xlrd = "^1.2.0"
black = "^19.10b0"
flake8 = "^3.8.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
